"""init migration

Revision ID: 0cf2715a57b1
Revises:
Create Date: 2025-04-12 16:04:48.229862

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf2715a57b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'courses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('detailed_name', sa.String(length=64), nullable=True),
        sa.Column('modality', sa.String(length=64), nullable=True),
        sa.Column('degree', sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'institutions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=True),
        sa.Column('acronym', sa.String(length=64), nullable=True),
        sa.Column('organization', sa.String(length=64), nullable=True),
        sa.Column('category', sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'registrations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('state', sa.String(length=32), nullable=True),
        sa.Column('city', sa.String(length=32), nullable=True),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=True),
        sa.Column('institution_id', sa.Integer(), nullable=False),
        sa.Column('course_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['course_id'],
            ['courses.id'],
        ),
        sa.ForeignKeyConstraint(
            ['institution_id'],
            ['institutions.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrations')
    op.drop_table('institutions')
    op.drop_table('courses')
    # ### end Alembic commands ###
