"""empty message

Revision ID: 0d19b745aa4c
Revises: 7bdae25b007d
Create Date: 2025-05-04 19:13:42.530542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d19b745aa4c'
down_revision = '7bdae25b007d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('student_count', sa.Integer(), nullable=True),
    sa.Column('institution_name', sa.String(length=128), nullable=True),
    sa.Column('institution_acronym', sa.String(length=64), nullable=True),
    sa.Column('institution_organization', sa.String(length=64), nullable=True),
    sa.Column('institution_category', sa.String(length=64), nullable=True),
    sa.Column('course_name', sa.String(length=64), nullable=True),
    sa.Column('course_detailed_name', sa.String(length=64), nullable=True),
    sa.Column('course_modality', sa.String(length=64), nullable=True),
    sa.Column('course_degree', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('registrations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('state', sa.VARCHAR(length=32), nullable=True),
    sa.Column('city', sa.VARCHAR(length=32), nullable=True),
    sa.Column('year_2014', sa.INTEGER(), nullable=True),
    sa.Column('year_2015', sa.INTEGER(), nullable=True),
    sa.Column('year_2016', sa.INTEGER(), nullable=True),
    sa.Column('year_2017', sa.INTEGER(), nullable=True),
    sa.Column('year_2018', sa.INTEGER(), nullable=True),
    sa.Column('year_2019', sa.INTEGER(), nullable=True),
    sa.Column('year_2020', sa.INTEGER(), nullable=True),
    sa.Column('year_2021', sa.INTEGER(), nullable=True),
    sa.Column('year_2022', sa.INTEGER(), nullable=True),
    sa.Column('institution_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('institution_acronym', sa.VARCHAR(length=64), nullable=True),
    sa.Column('institution_organization', sa.VARCHAR(length=64), nullable=True),
    sa.Column('institution_category', sa.VARCHAR(length=64), nullable=True),
    sa.Column('course_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('course_detailed_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('course_modality', sa.VARCHAR(length=64), nullable=True),
    sa.Column('course_degree', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('registration')
    # ### end Alembic commands ###
