"""fix: years together in register

Revision ID: 28ed81fb691f
Revises: c505ad5fb0b4
Create Date: 2025-04-23 20:01:33.592430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ed81fb691f'
down_revision = 'c505ad5fb0b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2014', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_2015', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_2016', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_2017', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_2018', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_2019', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_2020', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_2021', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_2022', sa.Integer(), nullable=True))
        batch_op.drop_constraint('unique_registration', type_='unique')
        batch_op.create_unique_constraint('unique_registration', ['institution_id', 'course_id'])
        batch_op.drop_column('quantity')
        batch_op.drop_column('year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('unique_registration', type_='unique')
        batch_op.create_unique_constraint('unique_registration', ['institution_id', 'course_id', 'year'])
        batch_op.drop_column('year_2022')
        batch_op.drop_column('year_2021')
        batch_op.drop_column('year_2020')
        batch_op.drop_column('year_2019')
        batch_op.drop_column('year_2018')
        batch_op.drop_column('year_2017')
        batch_op.drop_column('year_2016')
        batch_op.drop_column('year_2015')
        batch_op.drop_column('year_2014')

    # ### end Alembic commands ###
