"""fix: tirar unique together

Revision ID: 50b42bc4b87f
Revises: 28ed81fb691f
Create Date: 2025-04-23 21:09:11.452438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b42bc4b87f'
down_revision = '28ed81fb691f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint('unique_course', type_='unique')

    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_constraint('unique_institution', type_='unique')

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_constraint('unique_registration', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_registration', ['institution_id', 'course_id'])

    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_institution', ['name', 'organization', 'category'])

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_course', ['detailed_name', 'modality', 'degree'])

    # ### end Alembic commands ###
