"""one table

Revision ID: 7bdae25b007d
Revises: 
Create Date: 2025-04-27 11:10:04.544061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bdae25b007d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('year_2014', sa.Integer(), nullable=True),
    sa.Column('year_2015', sa.Integer(), nullable=True),
    sa.Column('year_2016', sa.Integer(), nullable=True),
    sa.Column('year_2017', sa.Integer(), nullable=True),
    sa.Column('year_2018', sa.Integer(), nullable=True),
    sa.Column('year_2019', sa.Integer(), nullable=True),
    sa.Column('year_2020', sa.Integer(), nullable=True),
    sa.Column('year_2021', sa.Integer(), nullable=True),
    sa.Column('year_2022', sa.Integer(), nullable=True),
    sa.Column('institution_name', sa.String(length=128), nullable=True),
    sa.Column('institution_acronym', sa.String(length=64), nullable=True),
    sa.Column('institution_organization', sa.String(length=64), nullable=True),
    sa.Column('institution_category', sa.String(length=64), nullable=True),
    sa.Column('course_name', sa.String(length=64), nullable=True),
    sa.Column('course_detailed_name', sa.String(length=64), nullable=True),
    sa.Column('course_modality', sa.String(length=64), nullable=True),
    sa.Column('course_degree', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrations')
    # ### end Alembic commands ###
