"""add unique togheter in course, instituition and registration

Revision ID: c505ad5fb0b4
Revises: 0cf2715a57b1
Create Date: 2025-04-13 10:38:09.536032

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c505ad5fb0b4'
down_revision = '0cf2715a57b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_course', ['detailed_name', 'modality', 'degree'])

    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_institution', ['name', 'organization', 'category'])

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_registration', ['institution_id', 'course_id', 'year'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_constraint('unique_registration', type_='unique')

    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_constraint('unique_institution', type_='unique')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint('unique_course', type_='unique')

    # ### end Alembic commands ###
